development:
  clients:
    default:
      database: rails_mongo_contacts
      hosts:
        - localhost:27017
      options:
        #   w: 1

        # user: 'user'
        # password: 'password'
        # roles:
        #   - 'dbOwner'

test:
  clients:
    default:
      database: rails_mongo_contacts_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
